-- Active: 1768545351770@@127.0.0.1@5432@TaskBot
CREATE TYPE "GroupList" AS ENUM (
  'ИС231/4',
  'ИС241/2',
  'ИС251/1',
  'ИС251/2',
  'ИС252/1'
);

CREATE TYPE "Direction" AS ENUM (
  'FrontEnd',
  'BackEnd'
);

CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(30) NOT NULL,
  "last_name" varchar(30) NOT NULL,
  "middle_name" varchar(30),
  "group" "GroupList",
  "direction" "Direction",
  "discord_id" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Task" (
  "task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_name" varchar(120) NOT NULL,
  "task_description" varchar(500) DEFAULT 'Описание задачи отсуствует',
  "task_deadline" date,
  "task_reward" decimal(10,2) DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "UserTask" (
  "ut_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "task_id" int
);

CREATE TABLE "BallUser" (
  "bu_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "total_ball" decimal(10,2) DEFAULT 0
);

ALTER TABLE "UserTask" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "UserTask" ADD FOREIGN KEY ("task_id") REFERENCES "Task" ("task_id");

ALTER TABLE "BallUser" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");
